version: "3.8"

services:
  poll:
    build: ./poll
    env_file:
      - .env
    ports:
      - "5000:80"
    networks:
      - poll-tier
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:alpine
    networks:
      - back-tier
      - poll-tier
    ports:
      - "6379:6379"
    restart: always

  worker:
    build: ./worker
    networks:
      - back-tier
    env_file:
      - .env
    depends_on:
      - redis
      - db
    restart: always

  db:
    image: postgres:15-alpine
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - back-tier
      - result-tier
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always

  result:
    build: ./result
    ports:
      - "5001:80"
    env_file:
      - .env
    networks:
      - result-tier
    depends_on:
      - db
    restart: always

volumes:
  db-data:

networks:
  poll-tier:
  result-tier:
  back-tier: